language: android
sudo: required
jdk: oraclejdk8
dist: precise

before_cache:
  -rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  -rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

android:
  components:
  - tools
    - build-tools-28.0.3
    # The SDK version used to compile your projects
    - android-22
    - android-28

script:
  - echo "Travis branch is $TRAVIS_BRANCH"
  - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"
  - chmod 755 gradlew
  - ls -la
  # jacocoTestReport is supposed to run both local and instrumented tests on all the modules
  # Gradle issue running composite tasks in order https://github.com/gradle/gradle/issues/3300
  - travis_wait ./gradlew :opensrp-reveal:jacocoTestReport coveralls --stacktrace


notifications:
  slack:
    secure: fAiZ4yA7DM6nUKh7nqsCTqZBb03VEAvi5NcRu5mNh5coNn/50XNeZl+qpv7Dw70Ef85Y/k68uc6KwTGVqPXEmVq9Hk3e7lqpBNN8rufvgCYDDGPmywBmU5BhSeykKo0Ee7llM3mRR/EipjIWw1+YvMcS3hCoygf/UlMDDhG0Jo0=

#deploy:
#  provider: pages
#  skip_cleanup: true
#  github_token: "$GITHUB_TOKEN"
#  local_dir: opensrp-anc/build/docs/javadoc/
#  on:
#    branch: master
