---
form: anc_counselling_treatment
fields:
  - "danger_signs"
  - "danger_signs_value"
  - "bp_systolic_repeat"
  - "bp_diastolic_repeat"
  - "severe_hypertension"
  - "symp_sev_preeclampsia"
  - "symp_sev_preeclampsia_value"
  - "hypertension"
  - "preeclampsia"
  - "severe_preeclampsia"
  - "body_temp_repeat"
  - "pulse_rate_repeat"
  - "respiratory_exam"
  - "respiratory_exam_abnormal"
  - "respiratory_exam_abnormal_other"
  - "respiratory_exam_value"
  - "respiratory_exam_abnormal_value"
  - "respiratory_exam_abnormal_other_value"
  - "oximetry"
  - "cardiac_exam"
  - "cardiac_exam_abnormal"
  - "cardiac_exam_abnormal_value"
  - "cardiac_exam_abnormal_other"
  - "breast_exam"
  - "breast_exam_abnormal"
  - "breast_exam_abnormal_other"
  - "breast_exam_value"
  - "breast_exam_abnormal_value"
  - "breast_exam_abnormal_other_value"
  - "abdominal_exam"
  - "abdominal_exam_abnormal"
  - "abdominal_exam_abnormal_value"
  - "abdominal_exam_abnormal_other"
  - "pelvic_exam"
  - "pelvic_exam_abnormal"
  - "pelvic_exam_abnormal_value"
  - "pelvic_exam_abnormal_other"
  - "fetal_heartbeat"
  - "fetal_heart_rate_repeat"
  - "caffeine_intake"
  - "behaviour_persist"
  - "tobacco_user"
  - "shs_exposure"
  - "condom_use"
  - "alcohol_substance_use"
  - "alcohol_substance_use_value"
  - "alcohol_substance_use_other"
  - "alcohol_substance_use_other_value"
  - "substances_used"
  - "substances_used_value"
  - "substances_used_other"
  - "substances_used_other_value"
  - "phys_symptoms"
  - "phys_symptoms_persist"
  - "other_sym_lbpp"
  - "other_sym_vvo"
  - "pop_undernourish"
  - "bmi"
  - "weight_cat"
  - "exp_weight_gain"
  - "weight_gain"
  - "tot_weight_gain"
  - "health_conditions"
  - "hiv_positive"
  - "hepb_positive"
  - "syphilis_positive"
  - "pop_syphilis"
  - "asb_positive"
  - "gdm"
  - "gdm_risk"
  - "dm_in_preg"
  - "anaemic"
  - "tb_screening_result"
  - "preeclampsia_risk"
  - "pop_low_calcium"
  - "hiv_risk"
  - "pop_hiv_incidence"
  - "partner_hiv_status"
  - "hiv_test_partner_status"
  - "age"
  - "fetal_presentation"
  - "c_sections"
  - "no_of_fetuses"
  - "rh_factor"
  - "urine_culture"
  - "site_ipv_assess"
  - "pop_anaemia_40"
  - "pop_anaemia_20"
  - "ifa_effects"
  - "pop_helminth"
  - "pop_malaria"
  - "medications"
  - "tt_immun_status"
  - "flu_immun_status"
  - "pop_vita"
  - "prev_preg_comps"
  - "family_planning_type"
  - "other_symptoms"
  - "gravida"
  - "parity"
  - "danger_signs_value"
---
form: anc_profile
fields:
  - "site_anc_hiv"
  - "site_ultrasound"
  - "contact_no"
  - "no_of_fetuses"
  - "bmi"
  - "urine_glucose"
  - "gdm"
  - "dm_in_preg"
  - "hiv_test_result"
  - "pop_hepb"
  - "pop_hepb_screening"
---
form: anc_physical_exam
fields:
  - "prev_preg_comps"
  - "health_conditions"
  - "urine_glucose"
  - "urine_nitrites"
  - "contact_no"
  - "current_weight"
  - "pop_undernourish"
  - "gdm"
  - "dm_in_preg"
  - "hb_results"
  - "gest_age"
  - "last_contact_date"
---
form: anc_symptoms_follow_up
fields:
  - "calcium_supp"
  - "vita_supp"
  - "gest_age"
  - "syphilis_positive"
  - "ifa_high_prev"
  - "shs_exposure"
  - "ifa_low_prev"
  - "ifa_weekly"
  - "ifa_anaemia"
  - "pe_risk_aspirin_calcium"
  - "pe_risk_aspirin"
  - "tobacco_user"
  - "caffeine_intake"
  - "shs_exposure"
  - "condom_use"
  - "alcohol_substance_use"
  - "medications"
---
form: anc_test
fields:
  - "ultrasound_done_date"
  - "ultrasound_gest_age_wks"
  - "lmp_gest_age"
  - "lmp_edd"
  - "ultrasound_ga_hidden"
  - "ultrasound_gest_age"
  - "ultrasound_edd"
  - "sfh_ga_hidden"
  - "sfh_gest_age"
  - "sfh_edd"
  - "no_of_fetuses"
  - "fetal_presentation"
  - "prev_preg_comps"
  - "health_conditions"
  - "rh_factor"
  - "pop_hiv_prevalence"
  - "partner_hiv_status"
  - "site_anc_hiv"
  - "partner_hiv_positive"
  - "alcohol_substance_use"
  - "occupation"
  - "hepb_immun_status"
  - "hepb_test_type"
  - "pop_hepc"
  - "pop_syphilis"
  - "bmi"
  - "pallor"
  - "pop_tb"
---
form: anc_quick_check
fields:
  - "nothing"