---
properties_file_name: "profile_overview"
group: overview_of_pregnancy
sub_group: demographic_info
fields:
  - template: "{{profile_overview.overview_of_pregnancy.demographic_info.occupation}}: {occupation_value}"
    relevance: "true"
    isRedFont: "true"

---
sub_group: current_pregnancy
fields:
  - template: "{{profile_overview.overview_of_pregnancy.current_pregnancy.ga}}: {gest_age}"
    relevance: "true"
    isRedFont: "gest_age > 40"

  - template: "{{profile_overview.overview_of_pregnancy.current_pregnancy.edd}}: {edd}"
    relevance: "true"

  - template: "{{profile_overview.overview_of_pregnancy.current_pregnancy.ultrasound_date}}: {ultrasound_date}"
    relevance: "true"

  - template: "{{profile_overview.overview_of_pregnancy.current_pregnancy.no_of_fetuses}}: {no_of_fetuses}"
    relevance: "true"
    isRedFont: "no_of_fetuses > 1"

  - template: "{{profile_overview.overview_of_pregnancy.current_pregnancy.fetal_presentation}}: {fetal_presentation}"
    relevance: "true"

  - template: "{{profile_overview.overview_of_pregnancy.current_pregnancy.amniotic_fluid}}: {amniotic_fluid}"
    relevance: "true"

  - template: "{{profile_overview.overview_of_pregnancy.current_pregnancy.placenta_location}}: {placenta_location}"
    relevance: "true"
    isRedFont: "placenta_location.contains('Previa')"

---
sub_group: obstetric_history
fields:
  - template: "{{profile_overview.overview_of_pregnancy.obstetric_history.gravida}}: {gravida}"
    relevance: "true"
    isRedFont: "gravida >= 5"

  - template: "{{profile_overview.overview_of_pregnancy.obstetric_history.parity}}: {parity}"
    relevance: "true"
    isRedFont: "parity >= 5"

  - template: "{{profile_overview.overview_of_pregnancy.obstetric_history.no_of_pregnancies_lost_ended}}: {miscarriages_abortions}"
    relevance: "true"
    isRedFont: "miscarriages_abortions > 1"

  - template: "{{profile_overview.overview_of_pregnancy.obstetric_history.no_of_stillbirths}}: {stillbirths}"
    relevance: "true"
    isRedFont: "stillbirths > 0"

  - template: "{{profile_overview.overview_of_pregnancy.obstetric_history.no_of_c_sections}}: {c_sections}"
    relevance: "true"
    isRedFont: "stillbirths > 0"

  - template: "{{profile_overview.overview_of_pregnancy.obstetric_history.past_pregnancy_problems}}: {prev_preg_comps_value}, {prev_preg_comps_other}"
    relevance: "true"
    isRedFont: "true"

  - template: "{{profile_overview.overview_of_pregnancy.obstetric_history.past_substances_used}}: {substances_used_value},{substances_used_other}"
    relevance: "true"
    isRedFont: "true"

---
sub_group: medical_history
fields:
  - template: "{{profile_overview.overview_of_pregnancy.medical_history.blood_type}}: {blood_type}"
    relevance: "true"

  - template: "{{profile_overview.overview_of_pregnancy.medical_history.allergies}}: {allergies}"
    relevance: "true"

  - template: "{{profile_overview.overview_of_pregnancy.medical_history.surgeries}}: {surgeries}"
    relevance: "true"

  - template: "{{profile_overview.overview_of_pregnancy.medical_history.chronic_health_conditions}}: {health_conditions_value}"
    relevance: "true"

  - template: "{{profile_overview.overview_of_pregnancy.medical_history.past_hiv_diagnosis_date}}: {hiv_diagnosis_date}"
    relevance: "true"
    isRedFont: "true"

---
sub_group: weight
fields:
  - template: "{{profile_overview.overview_of_pregnancy.weight.bmi}}: {bmi}"
    relevance: "true"
    isRedFont: "bmi < 18.5 || bmi >= 25"

  - template: "{{profile_overview.overview_of_pregnancy.weight.weight_category}}: {weight_cat}"
    relevance: "true"
    isRedFont: "weight_cat.contains('Underweight') || weight_cat.contains('Overweight') || weight_cat.contains('Obese')"

  - template: "{{profile_overview.overview_of_pregnancy.weight.expected_weight_gain_during_the_pregnancy}}: {exp_weight_gain} kg"
    relevance: "true"

  - template: "{{profile_overview.overview_of_pregnancy.weight.total_weight_gain_in_pregnancy_so_far}}: {tot_weight_gain} kg"
    relevance: "true"

---
sub_group: medications
fields:
  - template: "{{profile_overview.overview_of_pregnancy.medications.current_medications}}: {medications_value}"
    relevance: "true"

  - template: "{{profile_overview.overview_of_pregnancy.medications.medications_prescribed}}: {medications_prescribed}"
    relevance: "true"

  - template: "{{profile_overview.overview_of_pregnancy.medications.calcium_compliance}}: {calcium_comply}"
    relevance: "true"

  - template: "{{profile_overview.overview_of_pregnancy.medications.calcium_side_effects}}: {calcium_effects}"
    relevance: "true"

  - template: "{{profile_overview.overview_of_pregnancy.medications.ifa_compliance}}: {ifa_comply}"
    relevance: "true"

  - template: "{{profile_overview.overview_of_pregnancy.medications.ifa_side_effects}}: {ifa_effects}"
    relevance: "true"

  - template: "{{profile_overview.overview_of_pregnancy.medications.aspirin_compliance}}: {aspirin_comply}"
    relevance: "true"

  - template: "{{profile_overview.overview_of_pregnancy.medications.vitamin_a_compliance}}: {vita_comply}"
    relevance: "true"

  - template: "{{profile_overview.overview_of_pregnancy.medications.penicillin_compliance}}: {penicillin_comply}"
    relevance: "true"
---
group: hospital_referral_reasons
fields:
  - template: "{{profile_overview.hospital_referral_reasons.woman_referred_to_hospital}}"
    relevance: "true"

  - template: "{{profile_overview.hospital_referral_reasons.woman_not_referred_to_hospital}}: {referred_hosp_notdone}"
    relevance: "true"
    isRedFont: "true"

  - template: "{{profile_overview.hospital_referral_reasons.danger_signs}}: {danger_signs}"
    relevance: "true"

  - template: "{{profile_overview.hospital_referral_reasons.severe_hypertension}}: {bp_systolic_repeat}/{bp_diastolic_repeat} mmHg"
    relevance: "true"

  - template: "{{profile_overview.hospital_referral_reasons.hypertension_and_symptom_of_severe_pre_eclampsia}}: {symp_sev_preeclampsia}"
    relevance: "true"

  - template: "{{profile_overview.hospital_referral_reasons.pre_eclampsia_diagnosis}}"
    relevance: "true"

  - template: "{{profile_overview.hospital_referral_reasons.severe_pre_eclampsia_diagnosis}}"
    relevance: "true"

  - template: "{{profile_overview.hospital_referral_reasons.fever}}: {body_temp_repeat}ºC"
    relevance: "true"
    isRedFont: "true"

  - template: "{{profile_overview.hospital_referral_reasons.abnormal_pulse_rate}}: {pulse_rate_repeat} bpm"
    relevance: "true"

  - template: "{{profile_overview.hospital_referral_reasons.respiratory_distress}}: {respiratory_exam_abnormal_value}"
    relevance: "true"

  - template: "{{profile_overview.hospital_referral_reasons.low_oximetry}}: {oximetry}%"
    relevance: "true"
    isRedFont: "true"

  - template: "{{profile_overview.hospital_referral_reasons.abnormal_cardiac_exam}}: {cardiac_exam_abnormal_value}"
    relevance: "true"

  - template: "{{profile_overview.hospital_referral_reasons.abnormal_breast_exam}}: {breast_exam_abnormal_value}"
    relevance: "true"

  - template: "{{profile_overview.hospital_referral_reasons.abnormal_abdominal_exam}}: {abdominal_exam_abnormal_value}"
    relevance: "true"

  - template: "{{profile_overview.hospital_referral_reasons.abnormal_pelvic_exam}}: {pelvic_exam_abnormal_value}"
    relevance: "true"

  - template: "{{profile_overview.hospital_referral_reasons.no_fetal_heartbeat_observed}}"
    relevance: "true"
    isRedFont: "true"

  - template: "{{profile_overview.hospital_referral_reasons.abnormal_fetal_heart_rate}}: {fetal_heart_rate_repeat} bpm"
    relevance: "true"

---
group: risks_and_diagnoses
fields:
  - template: "High daily consumption of caffeine: {caffeine_intake_value}"
    relevance: "true"
    isRedFont: "true"

  - template: "Tobacco user or recently quit: {tobacco_user}"
    relevance: "true"
    isRedFont: "true"

  - template: "Second-hand exposure to tobacco smoke: {shs_exposure}"
    relevance: "true"
    isRedFont: "true"

  - template: "Woman and her partner(s) do not use condoms: {condom_use}"
    relevance: "true"
    isRedFont: "true"

  - template: "Alcohol / substances currently using: {alcohol_substance_use_value}, {other_substance_use_value}"
    relevance: "true"
    isRedFont: "true"

  - template: "Reduced or no fetal movement perceived by woman: {mat_percept_fetal_move}"
    relevance: "true"
    isRedFont: "true"

  - template: "Pre-eclampsia risk: {preeclampsia_risk}"
    relevance: "true"
    isRedFont: "true"

  - template: "HIV risk: {date}"
    relevance: "true"
    isRedFont: "true"

  - template: "Diabetes risk: {date} "
    relevance: "true"
    isRedFont: "true"

  - template: "Hypertension: {date}"
    relevance: "true"
    isRedFont: "true"

  - template: "Severe hypertension: {date}: {date}"
    relevance: "true"
    isRedFont: "true"

  - template: "Pre-eclampsia: {date}"
    relevance: "true"
    isRedFont: "true"

  - template: "Severe pre-eclampsia: {date}"
    relevance: "true"
    isRedFont: "true"

  - template: "Rh factor negative: {date}: {date}"
    relevance: "true"
    isRedFont: "true"

  - template: "HIV positive: {date}"
    relevance: "true"
    isRedFont: "true"

  - template: "Hepatitis B positive: {date}"
    relevance: "true"
    isRedFont: "true"

  - template: "Hepatitis C positive: {date}"
    relevance: "true"
    isRedFont: "true"

  - template: "Syphilis positive: {date}"
    relevance: "true"
    isRedFont: "true"

  - template: "Asymptomatic bacteriuria (ASB) infection: {date}"
    relevance: "true"
    isRedFont: "true"

  - template: "Positive for Group B Streptococcus (GBS): {date}"
    relevance: "true"
    isRedFont: "true"

  - template: "Gestational Diabetes Mellitus (GDM): {date}"
    relevance: "true"
    isRedFont: "true"

  - template: "Diabetes Mellitus (DM) in pregnancy: {date}"
    relevance: "true"
    isRedFont: "true"

  - template: "Anaemia diagnosis: {date}"
    relevance: "true"
    isRedFont: "true"

  - template: "TB screening positive: {date}"
    relevance: "true"
    isRedFont: "true"


---
group: physiological_symptoms
fields:
  - template: "{{profile_overview.physiological_symptoms.physiological_symptoms}}: {phys_symptoms_value}"
    relevance: "true"

  - template: "Persisting physiological symptoms: {phys_symptoms_persist_value}"
    relevance: "true"
    isRedFont: "true"

---
group: birth_plan_counseling
fields:
  - template: "{{profile_overview.birth_plan_counseling.planned_birth_place}}: {delivery_place}"
    relevance: "true"

  - template: "{{profile_overview.birth_plan_counseling.fp_method_accepted}}: {family_planning_type}"
    relevance: "true"

---
group: malaria_prophylaxis
fields:
  - template: "{{profile_overview.malaria_prophylaxis.iptp_sp_dose_1}}: {date}"
    relevance: "true"

  - template: "{{profile_overview.malaria_prophylaxis.iptp_sp_dose_2}}: {date}"
    relevance: "true"

  - template: "{{profile_overview.malaria_prophylaxis.iptp_sp_dose_3}}: {date}"
    relevance: "true"

---
group: immunisation_status
fields:
  - template: "{{profile_overview.immunisation_status.tt_immunisation_status}}: {tt_immun_status_value}"
    relevance: "true"
    isRedFont: "tt_immun_status == 'ttcv_not_received' || tt_immun_status == 'unknown'"

  - template: "{{profile_overview.immunisation_status.tt_dose_1}}: {tt1_date_value}"
    relevance: "true"

  - template: "{{profile_overview.immunisation_status.tt_dose_2}}: {tt2_date_value}"
    relevance: "true"

  - template: "{{profile_overview.immunisation_status.flu_immunisation_status}}: {flu_immun_status_value}"
    relevance: "true"
    isRedFont: "flu_immun_status == 'seasonal_flu_dose_missing' || flu_immun_status == 'unknown'"

  - template: "{{profile_overview.immunisation_status.flu_dose}}: {flu_date_value}"
    relevance: "true"