---
fields:
-   template: "Ultrasound test: {ultrasound}"
    relevance: "ultrasound != ''"

-   template: "Ultrasound not done reason: {ultrasound_notdone}"
    relevance: "ultrasound_notdone != ''"

-   template: "Danger sign(s): {danger_signs_value}"
    relevance: "danger_signs != '' && !danger_signs.contains('danger_none')"
    isRedFont: "danger_signs != '' && !danger_signs.contains('danger_none')"