---
properties_file_name: "profile_overview"
group: overview_of_pregnancy
sub_group: client_details
fields:
  - template: "{{profile_overview.overview_of_pregnancy.obstetric_history.provider_name}}: {provider_name}"
    relevance: "provider_name != ''"

  - template: "{{profile_overview.overview_of_pregnancy.obstetric_history.provider_phone_number}}: {provider_phone_number}"
    relevance: "provider_phone_number != ''"

  - template: "{{profile_overview.overview_of_pregnancy.current_pregnancy.ga}}: {gest_age}"
    relevance: "gest_age != ''"
    isRedFont: "gest_age > 40"

  - template: "{{profile_overview.overview_of_pregnancy.current_pregnancy.ga_days}}: {gest_age_days}"
    relevance: "gest_age_days != ''"

  - template: "{{profile_overview.overview_of_pregnancy.current_pregnancy.edd}}: {edd}"
    relevance: "edd != ''"

  - template: "{{profile_overview.overview_of_pregnancy.current_pregnancy.lmp}}: {lmp_known_date}"
    relevance: "lmp_known_date != ''"

  - template: "{{profile_overview.overview_of_pregnancy.current_pregnancy.fetal_presentation}}: {fetal_presentation}"
    relevance: "fetal_presentation != ''"

  - template: "{{profile_overview.overview_of_pregnancy.obstetric_history.gravida}}: {total_gravida}"
    relevance: "total_gravida != ''"
    isRedFont: "total_gravida >= 5"

  - template: "{{profile_overview.overview_of_pregnancy.obstetric_history.parity}}: {parity}"
    relevance: "parity != ''"
    isRedFont: "parity >= 5"
---
sub_group: past_medical_history
fields:
  - template: "{{profile_overview.overview_of_pregnancy.medical_history.surgeries}}: {surgeries_value}"
    relevance: "surgeries_value != '' && !surgeries_value.contains('None')"

  - template: "{{profile_overview.overview_of_pregnancy.medical_history.chronic_health_conditions}}: {health_conditions_value}"
    relevance: "!health_conditions.isEmpty() && !health_conditions.contains('none') && !health_conditions.contains('dont_know')"

  - template: "{{profile_overview.overview_of_pregnancy.medical_history.past_hiv_diagnosis_date}}: {hiv_diagnosis_date}"
    relevance: "hiv_diagnosis_date != ''"
    isRedFont: "true"

---
sub_group: body_mass_index
fields:
  - template: "{{profile_overview.overview_of_pregnancy.weight.bmi}}: {bmi}"
    relevance: "bmi > 1"
    isRedFont: "bmi < 18.5 || bmi >= 25"

  - template: "{{profile_overview.overview_of_pregnancy.weight.weight_category}}: {weight_cat}"
    relevance: "weight_cat > 1 && weight_cat.contains('Underweight') || weight_cat.contains('Overweight') || weight_cat.contains('Obese')"
    isRedFont: "weight_cat.contains('Underweight') || weight_cat.contains('Overweight') || weight_cat.contains('Obese')"

  - template: "{{profile_overview.overview_of_pregnancy.weight.expected_weight_gain_during_the_pregnancy}}: {exp_weight_gain} kg"
    relevance: "exp_weight_gain != ''"

  - template: "{{profile_overview.overview_of_pregnancy.weight.total_weight_gain_in_pregnancy_so_far}}: {tot_weight_gain} kg"
    relevance: "tot_weight_gain != ''"

---
sub_group: treatment
fields:
  - template: "{{profile_overview.overview_of_pregnancy.medications.current_medications}}: {medications_value}"
    relevance: "medications_value != '' && !medications_value.contains('None')"

  - template: "{{profile_overview.overview_of_pregnancy.medications.medications_prescribed}}: {medications_prescribed}"
    relevance: "medications_prescribed !='' "

  - template: "{{profile_overview.overview_of_pregnancy.medications.calcium_compliance}}: {calcium_comply}"
    relevance: "calcium_comply != ''"

  - template: "{{profile_overview.overview_of_pregnancy.medications.calcium_side_effects}}: {calcium_effects}"
    relevance: "calcium_effects != ''"

  - template: "{{profile_overview.overview_of_pregnancy.medications.ifa_compliance}}: {ifa_comply}"
    relevance: "ifa_comply != ''"

  - template: "{{profile_overview.overview_of_pregnancy.medications.ifa_side_effects}}: {ifa_effects}"
    relevance: "ifa_effects != ''"

  - template: "{{profile_overview.overview_of_pregnancy.medications.aspirin_compliance}}: {aspirin_comply}"
    relevance: "aspirin_comply != ''"

  - template: "{{profile_overview.overview_of_pregnancy.medications.vitamin_a_compliance}}: {vita_comply}"
    relevance: "vita_comply != ''"

  - template: "{{profile_overview.overview_of_pregnancy.medications.penicillin_compliance}}: {penicillin_comply}"
    relevance: "penicillin_comply != ''"
---
sub_group: vitals
fields:
  - template: "{{profile_overview.hospital_referral_reasons.fever}}: {body_temp_repeat}ºC"
    relevance: "body_temp_repeat >= 38"
    isRedFont: "true"

  - template: "{{profile_overview.hospital_referral_reasons.abnormal_pulse_rate}}: {pulse_rate_repeat} bpm"
    relevance: "pulse_rate_repeat < 60 || pulse_rate_repeat > 100"

  - template: "{{profile_overview.hospital_referral_reasons.respiratory_distress}}: {respiratory_exam_abnormal_value}"
    relevance: "respiratory_exam_abnormal != ''"

  - template: "{{profile_overview.hospital_referral_reasons.no_fetal_heartbeat_observed}}"
    relevance: "fetal_heartbeat == 'No'"
    isRedFont: "true"

  - template: "{{profile_overview.hospital_referral_reasons.abnormal_fetal_heart_rate}}: {fetal_heart_rate_repeat} bpm"
    relevance: "fetal_heart_rate_repeat < 100 || fetal_heart_rate_repeat > 180"

---
sub_group: laboratory_results
fields:
  - template: "Hypertension: {date}"
    relevance: "hypertension == 1"
    isRedFont: "true"

  - template: "Severe hypertension: {date}: {date}"
    relevance: "severe_hypertension == 1"
    isRedFont: "true"

  - template: "HIV positive: {date}"
    relevance: "hiv_positive == 1"
    isRedFont: "true"

  - template: "Hepatitis B positive: {date}"
    relevance: "hepb_positive == 1"
    isRedFont: "true"

  - template: "Syphilis positive: {date}"
    relevance: "syphilis_positive == 1"
    isRedFont: "true"

  - template: "Asymptomatic bacteriuria (ASB) infection: {date}"
    relevance: "asb_positive == 1"
    isRedFont: "true"

  - template: "Positive for Group B Streptococcus (GBS): {date}"
    relevance: "urine_culture == 'positive - group b streptococcus (gbs)'"
    isRedFont: "true"

  - template: "Gestational Diabetes Mellitus (GDM): {date}"
    relevance: "gdm = 1"
    isRedFont: "true"

  - template: "Diabetes Mellitus (DM) in pregnancy: {date}"
    relevance: "dm_in_preg = 1"
    isRedFont: "true"

  - template: "Anaemia diagnosis: {date}"
    relevance: "anaemic = 1"
    isRedFont: "true"

  - template: "TB screening positive: {date}"
    relevance: "tb_screening_result == 'positive'"
    isRedFont: "true"

---
sub_group: symptoms
fields:
  - template: "{{profile_overview.physiological_symptoms.physiological_symptoms}}: {phys_symptoms_value}"
    relevance: "phys_symptoms_value != '' && !phys_symptoms_value.contains('None')"
  - template: "Persisting physiological symptoms: {phys_symptoms_persist_value}"
    relevance: "phys_symptoms_persist != ''"
    isRedFont: "true"